import type { QuizStep } from "./types";

export const FUND_QUIZ_STEPS: QuizStep[] = [
  {
    id: "org_role",
    question: "What is your role in the organisation?",
    question_de: "Was ist Ihre Rolle in der Organisation?",
    subtitle: "This helps us tailor results — prototype only, no account required.",
    subtitle_de: "Hilft uns, die Ergebnisse anzupassen.",
    type: "single",
    options: [
      {
        value: "staff",
        icon: "👤",
        label: "Staff / Management",
        label_de: "Mitarbeiter / Management",
        desc: "You work for the NGO day to day",
      },
      {
        value: "board",
        icon: "🏛️",
        label: "Board / Presidium",
        label_de: "Vorstand / Präsidium",
        desc: "You govern or represent the organisation",
      },
    ],
  },
  {
    id: "sectors",
    question: "Which sectors does your organisation work in?",
    question_de: "In welchen Bereichen ist Ihre Organisation tätig?",
    subtitle: "Select all that apply. We match against foundation statutes.",
    subtitle_de: "Wählen Sie alle zutreffenden Bereiche. Wir gleichen mit Stiftungsstatuten ab.",
    type: "multi",
    minSelect: 1,
    options: [
      {
        value: "children_youth_families",
        icon: "👶",
        label: "Children & Youth",
        label_de: "Kinder & Jugend",
        desc: "Young people and families",
      },
      {
        value: "senior_citizens",
        icon: "🧓",
        label: "Senior Citizens",
        label_de: "Senioren",
        desc: "Care and inclusion for older adults",
      },
      {
        value: "education",
        icon: "📚",
        label: "Education",
        label_de: "Bildung",
        desc: "Learning and training",
      },
      {
        value: "social_health",
        icon: "❤️",
        label: "Social & Health",
        label_de: "Soziales & Gesundheit",
        desc: "Social services and healthcare",
      },
      {
        value: "arts_culture",
        icon: "🎨",
        label: "Arts & Culture",
        label_de: "Kunst & Kultur",
        desc: "Culture and creative work",
      },
      {
        value: "environment_climate",
        icon: "🌿",
        label: "Environment",
        label_de: "Umwelt",
        desc: "Climate and nature",
      },
      {
        value: "sport_leisure",
        icon: "⚽",
        label: "Sports & Leisure",
        label_de: "Sport & Freizeit",
        desc: "Sport and recreation",
      },
      {
        value: "development",
        icon: "🌍",
        label: "Global Development",
        label_de: "Globale Entwicklung",
        desc: "International cooperation",
      },
    ],
  },
  {
    id: "funding_need",
    question: "What type of funding are you seeking?",
    question_de: "Welche Art von Förderung suchen Sie?",
    subtitle: "Project funding is often easier to match than general operating costs.",
    subtitle_de: "Projektfinanzierung lässt sich oft leichter vermitteln als allgemeine Betriebskosten.",
    type: "multi",
    minSelect: 1,
    options: [
      {
        value: "project",
        icon: "📋",
        label: "Named project",
        label_de: "Benanntes Projekt",
        desc: "A specific initiative with budget and timeline",
      },
      {
        value: "operating",
        icon: "🏢",
        label: "Operating costs",
        label_de: "Betriebskosten",
        desc: "Core running costs or annual programme",
      },
      {
        value: "capacity",
        icon: "📈",
        label: "Capacity building",
        label_de: "Kapazitätsaufbau",
        desc: "Staff, systems, or organisational development",
      },
      {
        value: "emergency",
        icon: "🚨",
        label: "One-off / urgent",
        label_de: "Einmalig / dringend",
        desc: "Short-term or unexpected need",
      },
    ],
  },
  {
    id: "amount_sought",
    question: "How much funding are you looking for?",
    question_de: "Wie viel Förderung suchen Sie?",
    subtitle: "Approximate total for this ask — partial funding is common.",
    subtitle_de: "Ungefähre Gesamtsumme für diesen Antrag — Teilfinanzierung ist üblich.",
    type: "single",
    options: [
      {
        value: "under_25k",
        icon: "💵",
        label: "Under CHF 25,000",
        label_de: "Unter CHF 25'000",
        desc: "Small grants or pilot projects",
      },
      {
        value: "25k_100k",
        icon: "💴",
        label: "CHF 25,000 – 100,000",
        label_de: "CHF 25'000 – 100'000",
        desc: "Mid-size project or annual programme",
      },
      {
        value: "100k_500k",
        icon: "💶",
        label: "CHF 100,000 – 500,000",
        label_de: "CHF 100'000 – 500'000",
        desc: "Larger multi-year initiatives",
      },
      {
        value: "over_500k",
        icon: "💷",
        label: "Over CHF 500,000",
        label_de: "Über CHF 500'000",
        desc: "Major programme or capital project",
      },
    ],
  },
  {
    id: "geographic_focus",
    question: "Where does your work primarily take place?",
    question_de: "Wo findet Ihre Arbeit hauptsächlich statt?",
    subtitle: "Must align with a foundation's geographic mandate.",
    subtitle_de: "Muss mit dem geografischen Mandat einer Stiftung übereinstimmen.",
    type: "single",
    options: [
      {
        value: "liechtenstein",
        icon: "🇱🇮",
        label: "Liechtenstein",
        label_de: "Liechtenstein",
        desc: "Activities mainly within the Principality",
      },
      {
        value: "dach",
        icon: "🌐",
        label: "DACH region",
        label_de: "DACH-Region",
        desc: "LI plus neighbouring countries",
      },
      {
        value: "international",
        icon: "🌍",
        label: "International",
        label_de: "International",
        desc: "Programmes outside the DACH region",
      },
    ],
  },
  {
    id: "sdg_priorities",
    question: "Which SDGs does your project advance?",
    question_de: "Welche SDGs fördert Ihr Projekt?",
    subtitle: "Optional but helps match open-mandate foundations. Up to 3.",
    subtitle_de: "Optional, hilft bei der Zuordnung zu offenen Stiftungsmandaten. Bis zu 3.",
    type: "multi",
    maxSelect: 3,
    minSelect: 0,
    options: [
      { value: 1, icon: "🏠", label: "No Poverty", label_de: "Keine Armut", desc: "SDG 1" },
      { value: 2, icon: "🍽️", label: "Zero Hunger", label_de: "Kein Hunger", desc: "SDG 2" },
      { value: 3, icon: "❤️‍🩹", label: "Good Health", label_de: "Gesundheit", desc: "SDG 3" },
      { value: 4, icon: "📖", label: "Quality Education", label_de: "Bildung", desc: "SDG 4" },
      { value: 5, icon: "⚖️", label: "Gender Equality", label_de: "Gleichstellung", desc: "SDG 5" },
      { value: 10, icon: "🤝", label: "Reduced Inequalities", label_de: "Weniger Ungleichheiten", desc: "SDG 10" },
      { value: 11, icon: "🏙️", label: "Sustainable Cities", label_de: "Nachhaltige Städte", desc: "SDG 11" },
      { value: 13, icon: "🌡️", label: "Climate Action", label_de: "Klimaschutz", desc: "SDG 13" },
      { value: 15, icon: "🌳", label: "Life on Land", label_de: "Leben an Land", desc: "SDG 15" },
      { value: 16, icon: "🕊️", label: "Peace & Justice", label_de: "Frieden & Gerechtigkeit", desc: "SDG 16" },
      { value: 17, icon: "🌐", label: "Partnerships", label_de: "Partnerschaften", desc: "SDG 17" },
    ],
  },
];
