import type { QuizStep } from "./types";

export const QUIZ_STEPS: QuizStep[] = [
  {
    id: "supporter_type",
    question: "What type of supporter are you?",
    question_de: "Was für ein Unterstützer sind Sie?",
    subtitle: "This helps us understand your governance structure and giving approach.",
    subtitle_de: "Dies hilft uns, Ihre Governance-Struktur und Ihren Förderansatz zu verstehen.",
    type: "single",
    options: [
      {
        value: "individual_trustee",
        icon: "👤",
        label: "Individual Trustee",
        label_de: "Einzeltreuhänder",
        desc: "You serve personally as a trustee or board member",
      },
      {
        value: "private_foundation",
        icon: "🏛️",
        label: "Private Foundation",
        label_de: "Privatstiftung",
        desc: "A privately established charitable foundation",
      },
      {
        value: "corporate_foundation",
        icon: "🏢",
        label: "Corporate Foundation",
        label_de: "Unternehmensstiftung",
        desc: "Established and funded by a corporation",
      },
      {
        value: "family_foundation",
        icon: "👨‍👩‍👧",
        label: "Family Foundation",
        label_de: "Familienstiftung",
        desc: "A family-operated philanthropic foundation",
      },
    ],
  },
  {
    id: "sectors",
    question: "Which sectors align with your values?",
    question_de: "Welche Bereiche entsprechen Ihren Werten?",
    subtitle: "Select all areas you wish to support. At least one required.",
    subtitle_de: "Wählen Sie alle Bereiche aus, die Sie unterstützen möchten. Mindestens eine Auswahl erforderlich.",
    type: "multi",
    minSelect: 1,
    options: [
      {
        value: "children_youth_families",
        icon: "👶",
        label: "Children & Youth",
        label_de: "Kinder & Jugend",
        desc: "Supporting young people and families",
      },
      {
        value: "senior_citizens",
        icon: "🧓",
        label: "Senior Citizens",
        label_de: "Senioren",
        desc: "Care and inclusion for older adults",
      },
      {
        value: "education",
        icon: "📚",
        label: "Education",
        label_de: "Bildung",
        desc: "Learning, training, and knowledge",
      },
      {
        value: "social_health",
        icon: "❤️",
        label: "Social & Health",
        label_de: "Soziales & Gesundheit",
        desc: "Social services and healthcare",
      },
      {
        value: "arts_culture",
        icon: "🎨",
        label: "Arts & Culture",
        label_de: "Kunst & Kultur",
        desc: "Creative expression and cultural heritage",
      },
      {
        value: "environment_climate",
        icon: "🌿",
        label: "Environment",
        label_de: "Umwelt",
        desc: "Nature, sustainability, and climate",
      },
      {
        value: "sport_leisure",
        icon: "⚽",
        label: "Sports & Leisure",
        label_de: "Sport & Freizeit",
        desc: "Physical activity and recreation",
      },
      {
        value: "development",
        icon: "🌍",
        label: "Global Development",
        label_de: "Globale Entwicklung",
        desc: "International aid and development cooperation",
      },
    ],
  },
  {
    id: "engagement",
    question: "How do you prefer to engage?",
    question_de: "Wie möchten Sie sich engagieren?",
    subtitle: "Select all that apply.",
    subtitle_de: "Wählen Sie alle zutreffenden Optionen.",
    type: "multi",
    minSelect: 1,
    options: [
      {
        value: "financial",
        icon: "💰",
        label: "Financial Grants",
        label_de: "Finanzielle Förderung",
        desc: "Providing direct funding or grants",
      },
      {
        value: "governance",
        icon: "🏛️",
        label: "Board Governance",
        label_de: "Vorstandsarbeit",
        desc: "Active membership on the board of trustees",
      },
      {
        value: "advisory",
        icon: "💡",
        label: "Strategic Advisory",
        label_de: "Strategische Beratung",
        desc: "Offering strategic guidance and advice",
      },
      {
        value: "project",
        icon: "📋",
        label: "Project Funding",
        label_de: "Projektfinanzierung",
        desc: "Targeted funding for specific initiatives",
      },
      {
        value: "mentorship",
        icon: "🤝",
        label: "Mentorship",
        label_de: "Mentoring",
        desc: "Capacity building and knowledge transfer",
      },
    ],
  },
  {
    id: "support_scale",
    question: "What is your annual support capacity?",
    question_de: "Wie hoch ist Ihr jährliches Förderbudget?",
    subtitle: "An estimate helps us match you with organisations of the right scale.",
    subtitle_de: "Eine Schätzung hilft uns, die passende Organisationsgrösse zu finden.",
    type: "single",
    options: [
      {
        value: "under_10k",
        icon: "💵",
        label: "Under CHF 10,000",
        label_de: "Unter CHF 10'000",
        desc: "Smaller contributions or in-kind support",
      },
      {
        value: "10k_50k",
        icon: "💴",
        label: "CHF 10,000 – 50,000",
        label_de: "CHF 10'000 – 50'000",
        desc: "Meaningful support for smaller organisations",
      },
      {
        value: "50k_250k",
        icon: "💶",
        label: "CHF 50,000 – 250,000",
        label_de: "CHF 50'000 – 250'000",
        desc: "Significant impact for mid-size NGOs",
      },
      {
        value: "over_250k",
        icon: "💷",
        label: "Over CHF 250,000",
        label_de: "Über CHF 250'000",
        desc: "Major philanthropic investment capacity",
      },
    ],
  },
  {
    id: "geographic_focus",
    question: "Where should the NGO primarily operate?",
    question_de: "Wo soll die NGO hauptsächlich tätig sein?",
    subtitle: "Choose the geographic scope that best fits your philanthropic priorities.",
    subtitle_de: "Wählen Sie den geografischen Fokus, der Ihren Philanthropieprioritäten entspricht.",
    type: "single",
    options: [
      {
        value: "liechtenstein",
        icon: "🇱🇮",
        label: "Liechtenstein Only",
        label_de: "Nur Liechtenstein",
        desc: "Focused exclusively within the Principality",
      },
      {
        value: "dach",
        icon: "🌐",
        label: "DACH Region",
        label_de: "DACH-Region",
        desc: "Liechtenstein, Switzerland, Austria & Germany",
      },
      {
        value: "europe",
        icon: "🇪🇺",
        label: "Europe",
        label_de: "Europa",
        desc: "Broader European reach",
      },
      {
        value: "africa",
        icon: "🌍",
        label: "Africa",
        label_de: "Afrika",
        desc: "Organisations working in Africa",
      },
      {
        value: "asia",
        icon: "🌏",
        label: "Asia",
        label_de: "Asien",
        desc: "Organisations working in Asia",
      },
      {
        value: "americas",
        icon: "🌎",
        label: "Americas",
        label_de: "Amerika",
        desc: "Organisations working in North or South America",
      },
      {
        value: "oceania",
        icon: "🌏",
        label: "Oceania",
        label_de: "Ozeanien",
        desc: "Organisations working in the Pacific region",
      },
      {
        value: "international",
        icon: "🌐",
        label: "Global / International",
        label_de: "Global / International",
        desc: "Worldwide reach and impact",
      },
    ],
  },
  {
    id: "sdg_priorities",
    question: "Which UN SDGs matter most to you?",
    question_de: "Welche UN-Nachhaltigkeitsziele sind Ihnen am wichtigsten?",
    subtitle: "Select up to 3 Sustainable Development Goals that resonate with your mission.",
    subtitle_de: "Wählen Sie bis zu 3 Nachhaltigkeitsziele, die Ihrer Mission entsprechen.",
    type: "multi",
    maxSelect: 3,
    minSelect: 0,
    options: [
      { value: 1, icon: "🏠", label: "No Poverty", label_de: "Keine Armut", desc: "SDG 1" },
      { value: 2, icon: "🍽️", label: "Zero Hunger", label_de: "Kein Hunger", desc: "SDG 2" },
      { value: 3, icon: "❤️‍🩹", label: "Good Health", label_de: "Gesundheit", desc: "SDG 3" },
      { value: 4, icon: "📖", label: "Quality Education", label_de: "Bildung", desc: "SDG 4" },
      { value: 5, icon: "⚖️", label: "Gender Equality", label_de: "Gleichstellung", desc: "SDG 5" },
      { value: 10, icon: "🤝", label: "Reduced Inequalities", label_de: "Weniger Ungleichheiten", desc: "SDG 10" },
      { value: 11, icon: "🏙️", label: "Sustainable Cities", label_de: "Nachhaltige Städte", desc: "SDG 11" },
      { value: 13, icon: "🌡️", label: "Climate Action", label_de: "Klimaschutz", desc: "SDG 13" },
      { value: 14, icon: "🐠", label: "Life Below Water", label_de: "Leben unter Wasser", desc: "SDG 14" },
      { value: 15, icon: "🌳", label: "Life on Land", label_de: "Leben an Land", desc: "SDG 15" },
      { value: 16, icon: "🕊️", label: "Peace & Justice", label_de: "Frieden & Gerechtigkeit", desc: "SDG 16" },
      { value: 17, icon: "🌐", label: "Partnerships", label_de: "Partnerschaften", desc: "SDG 17" },
    ],
  },
  {
    id: "legal_form_preference",
    question: "Do you prefer a particular organisational structure?",
    question_de: "Bevorzugen Sie eine bestimmte Organisationsform?",
    subtitle: "Associations (Verein) and foundations (Stiftung) have different governance models.",
    subtitle_de: "Vereine und Stiftungen haben unterschiedliche Governance-Modelle.",
    type: "single",
    options: [
      {
        value: "association",
        icon: "👥",
        label: "Associations (Verein)",
        label_de: "Vereine",
        desc: "Member-driven democratic organisations",
      },
      {
        value: "foundation",
        icon: "🏛️",
        label: "Foundations (Stiftung)",
        label_de: "Stiftungen",
        desc: "Foundation-governed with a board of trustees",
      },
      {
        value: "both",
        icon: "✅",
        label: "No Preference",
        label_de: "Keine Präferenz",
        desc: "Open to both organisational structures equally",
      },
    ],
  },
];